import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'animate.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { AlertProvider } from "next-alert";
import { ToastContainer } from 'react-toastify';
import { PhrasesProvider } from "@/contexts/PhraseContexts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Èdèdún - AI Powered Yorùbá Platform",
  description: "Generated by Èdèdún - AI Powered Yorùbá Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertProvider>
          <ToastContainer />
          <PhrasesProvider>
        {children}
        </PhrasesProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
